#!/usr/bin/env bash
#SBATCH --mem=0
#SBATCH -o /mnt/home/%u/BioReason-Pro/runtime_logs/coreweave/train_rl_paper_tight_2node_srun_%j.log
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-${SLURM_SUBMIT_DIR:-}}"
if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
cd "$PROJECT_ROOT"

default_runtime_root() {
  if [ -n "${BIOREASON_RUNTIME_ROOT:-}" ]; then
    printf '%s\n' "$BIOREASON_RUNTIME_ROOT"
    return 0
  fi
  if [ -d "/mnt/data" ] && [ -n "${USER:-}" ]; then
    printf '/mnt/data/%s/BioReason-Pro\n' "$USER"
    return 0
  fi
  printf '%s\n' "$PROJECT_ROOT"
}

if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

if [ -f configs/disease_benchmark/wandb_registry_paths.env ]; then
  set -a
  source configs/disease_benchmark/wandb_registry_paths.env
  set +a
fi

source "$PROJECT_ROOT/.venv-gpu/bin/activate"

export BIOREASON_RUNTIME_ROOT="${BIOREASON_RUNTIME_ROOT:-$(default_runtime_root)}"
export BIOREASON_ARTIFACTS_ROOT="${BIOREASON_ARTIFACTS_ROOT:-${BIOREASON_RUNTIME_ROOT}/data/artifacts}"
export BIOREASON_CACHE_ROOT="${BIOREASON_CACHE_ROOT:-${BIOREASON_RUNTIME_ROOT}/cache}"
export WANDB_DIR="${WANDB_DIR:-${BIOREASON_RUNTIME_ROOT}/wandb}"
export WEAVE_SERVER_CACHE_DIR="${WEAVE_SERVER_CACHE_DIR:-${WANDB_DIR}/weave_server_cache}"
export HF_HOME="${HF_HOME:-${BIOREASON_CACHE_ROOT}/huggingface}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-${HF_HOME}/datasets}"
mkdir -p "$BIOREASON_ARTIFACTS_ROOT" "$BIOREASON_CACHE_ROOT" "$WANDB_DIR" "$WEAVE_SERVER_CACHE_DIR" "$TRANSFORMERS_CACHE" "$HF_DATASETS_CACHE"

export WANDB_ENTITY="${WANDB_ENTITY:-wandb-healthcare}"
export WANDB_PROJECT="${WANDB_PROJECT:-bioreason-pro}"
export BASE_WANDB_PROJECT="${BASE_WANDB_PROJECT:-$WANDB_PROJECT}"
export WEAVE_PROJECT="${WEAVE_PROJECT:-${WANDB_ENTITY}/${WANDB_PROJECT}}"
export REGISTRY_ENV_FILE="${REGISTRY_ENV_FILE:-configs/disease_benchmark/wandb_registry_paths.env}"
export BASE_CHECKPOINT="${BASE_CHECKPOINT:-wandb-healthcare/bioreason-pro/bioreason-pro-rl:latest}"
export TEMPORAL_SPLIT_ARTIFACT="${TEMPORAL_SPLIT_ARTIFACT:-wandb-healthcare/bioreason-pro/disease-temporal-split:production}"
export DATASET_ARTIFACT="${DATASET_ARTIFACT:-wandb-healthcare/bioreason-pro/disease-temporal-reasoning:production}"
export REASONING_PROMPT_STYLE="${REASONING_PROMPT_STYLE:-paper_native_tight}"
export CHECKPOINT_ARTIFACT_NAME="${CHECKPOINT_ARTIFACT_NAME:-train-rl-paper-native-tight-2node}"
export CHECKPOINT_ARTIFACT_ALIASES="${CHECKPOINT_ARTIFACT_ALIASES:-latest,paper-native-tight,2node}"
export CHECKPOINT_EXPORT_ONLY="${CHECKPOINT_EXPORT_ONLY:-true}"
export EXECUTION_ID="${EXECUTION_ID:-${SLURM_JOB_ID:-local}-$(date -u +%Y%m%d%H%M%S)}"
export SYNC_ROOT="${SYNC_ROOT:-}"
export RESUME_FROM_EXPORT_ARTIFACT="${RESUME_FROM_EXPORT_ARTIFACT:-}"
export RESUME_MODE="${RESUME_MODE:-warm}"
export WANDB_RUN_NAME="${WANDB_RUN_NAME:-rl-paper-native-tight-2node-srun-$(date +%Y%m%d-%H%M%S)}"
export OUTPUT_DIR="${OUTPUT_DIR:-${BIOREASON_ARTIFACTS_ROOT}/models/train_rl_output/paper_native_tight_2node_srun}"
export NNODES="${NNODES:-2}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export QUERIES_PER_STEP="${QUERIES_PER_STEP:-8}"
export ROLLOUTS_PER_QUERY="${ROLLOUTS_PER_QUERY:-24}"
export OPTIMIZER_MICRO_BATCH_SIZE_PER_GPU="${OPTIMIZER_MICRO_BATCH_SIZE_PER_GPU:-6}"
export GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-2}"
export MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-10000}"
export ROLLOUT_MAX_NEW_TOKENS="${ROLLOUT_MAX_NEW_TOKENS:-$MAX_NEW_TOKENS}"
export ROLLOUT_WORKER_GENERATE_TIMEOUT_S="${ROLLOUT_WORKER_GENERATE_TIMEOUT_S:-1500}"
export ROLLOUT_WORKER_STARTUP_RETRY_COUNT="${ROLLOUT_WORKER_STARTUP_RETRY_COUNT:-3}"
export ROLLOUT_WORKER_STARTUP_RETRY_SLEEP_S="${ROLLOUT_WORKER_STARTUP_RETRY_SLEEP_S:-15}"
export VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-0.35}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-32768}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-32}"
export VLLM_SWAP_SPACE_GB="${VLLM_SWAP_SPACE_GB:-0}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export ROLLOUT_LOGPROB_MICROBATCH_SIZE="${ROLLOUT_LOGPROB_MICROBATCH_SIZE:-4}"
export VALIDATION_NUM_PROTEINS="${VALIDATION_NUM_PROTEINS:-8}"
export VALIDATION_EVERY_N_STEPS="${VALIDATION_EVERY_N_STEPS:-1}"
export SAVE_EVERY_N_STEPS="${SAVE_EVERY_N_STEPS:-1}"
export MASTER_ADDR="${MASTER_ADDR:-$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)}"
export MASTER_PORT="${MASTER_PORT:-29511}"

srun --nodes="${NNODES}" --ntasks="${NNODES}" --ntasks-per-node=1 bash -lc '
  set -euo pipefail
  cd '"$PROJECT_ROOT"'
  source "'"$PROJECT_ROOT"'"/.venv-gpu/bin/activate
  export WANDB_ENTITY="'"$WANDB_ENTITY"'"
  export WANDB_PROJECT="'"$WANDB_PROJECT"'"
  export BASE_WANDB_PROJECT="'"$BASE_WANDB_PROJECT"'"
  export WEAVE_PROJECT="'"$WEAVE_PROJECT"'"
  export REGISTRY_ENV_FILE="'"$REGISTRY_ENV_FILE"'"
  export BASE_CHECKPOINT="'"$BASE_CHECKPOINT"'"
  export TEMPORAL_SPLIT_ARTIFACT="'"$TEMPORAL_SPLIT_ARTIFACT"'"
  export DATASET_ARTIFACT="'"$DATASET_ARTIFACT"'"
  export REASONING_PROMPT_STYLE="'"$REASONING_PROMPT_STYLE"'"
  export CHECKPOINT_ARTIFACT_NAME="'"$CHECKPOINT_ARTIFACT_NAME"'"
  export CHECKPOINT_ARTIFACT_ALIASES="'"$CHECKPOINT_ARTIFACT_ALIASES"'"
  export CHECKPOINT_EXPORT_ONLY="'"$CHECKPOINT_EXPORT_ONLY"'"
  export EXECUTION_ID="'"$EXECUTION_ID"'"
  export SYNC_ROOT="'"$SYNC_ROOT"'"
  export RESUME_FROM_EXPORT_ARTIFACT="'"$RESUME_FROM_EXPORT_ARTIFACT"'"
  export RESUME_MODE="'"$RESUME_MODE"'"
  export BIOREASON_RUNTIME_ROOT="'"$BIOREASON_RUNTIME_ROOT"'"
  export BIOREASON_ARTIFACTS_ROOT="'"$BIOREASON_ARTIFACTS_ROOT"'"
  export BIOREASON_CACHE_ROOT="'"$BIOREASON_CACHE_ROOT"'"
  export WANDB_DIR="'"$WANDB_DIR"'"
  export WEAVE_SERVER_CACHE_DIR="'"$WEAVE_SERVER_CACHE_DIR"'"
  export HF_HOME="'"$HF_HOME"'"
  export TRANSFORMERS_CACHE="'"$TRANSFORMERS_CACHE"'"
  export HF_DATASETS_CACHE="'"$HF_DATASETS_CACHE"'"
  export WANDB_RUN_NAME="'"$WANDB_RUN_NAME"'"
  export OUTPUT_DIR="'"$OUTPUT_DIR"'"
  export NNODES="'"$NNODES"'"
  export GPUS_PER_NODE="'"$GPUS_PER_NODE"'"
  export QUERIES_PER_STEP="'"$QUERIES_PER_STEP"'"
  export ROLLOUTS_PER_QUERY="'"$ROLLOUTS_PER_QUERY"'"
  export OPTIMIZER_MICRO_BATCH_SIZE_PER_GPU="'"$OPTIMIZER_MICRO_BATCH_SIZE_PER_GPU"'"
  export GRADIENT_ACCUMULATION_STEPS="'"$GRADIENT_ACCUMULATION_STEPS"'"
  export MAX_NEW_TOKENS="'"$MAX_NEW_TOKENS"'"
  export ROLLOUT_MAX_NEW_TOKENS="'"$ROLLOUT_MAX_NEW_TOKENS"'"
  export ROLLOUT_WORKER_GENERATE_TIMEOUT_S="'"$ROLLOUT_WORKER_GENERATE_TIMEOUT_S"'"
  export ROLLOUT_WORKER_STARTUP_RETRY_COUNT="'"$ROLLOUT_WORKER_STARTUP_RETRY_COUNT"'"
  export ROLLOUT_WORKER_STARTUP_RETRY_SLEEP_S="'"$ROLLOUT_WORKER_STARTUP_RETRY_SLEEP_S"'"
  export VLLM_GPU_MEMORY_UTILIZATION="'"$VLLM_GPU_MEMORY_UTILIZATION"'"
  export VLLM_MAX_MODEL_LEN="'"$VLLM_MAX_MODEL_LEN"'"
  export VLLM_MAX_NUM_SEQS="'"$VLLM_MAX_NUM_SEQS"'"
  export VLLM_SWAP_SPACE_GB="'"$VLLM_SWAP_SPACE_GB"'"
  export PYTORCH_CUDA_ALLOC_CONF="'"$PYTORCH_CUDA_ALLOC_CONF"'"
  export ROLLOUT_LOGPROB_MICROBATCH_SIZE="'"$ROLLOUT_LOGPROB_MICROBATCH_SIZE"'"
  export VALIDATION_NUM_PROTEINS="'"$VALIDATION_NUM_PROTEINS"'"
  export VALIDATION_EVERY_N_STEPS="'"$VALIDATION_EVERY_N_STEPS"'"
  export SAVE_EVERY_N_STEPS="'"$SAVE_EVERY_N_STEPS"'"
  export MASTER_ADDR="'"$MASTER_ADDR"'"
  export MASTER_PORT="'"$MASTER_PORT"'"
  export NODE_RANK="$SLURM_NODEID"
  export HOSTFILE=""
  bash scripts/sh_train_protein_grpo.sh --max_steps 20 --validation_num_proteins "$VALIDATION_NUM_PROTEINS" --validation_every_n_steps "$VALIDATION_EVERY_N_STEPS" --save_every_n_steps "$SAVE_EVERY_N_STEPS"
'
