#!/usr/bin/env bash
set -euo pipefail

export BIOREASON_RUNTIME_ROOT="${BIOREASON_RUNTIME_ROOT:-/mnt/data/${USER:-bioreason}/BioReason-Pro}"
export BIOREASON_ARTIFACTS_ROOT="${BIOREASON_ARTIFACTS_ROOT:-$BIOREASON_RUNTIME_ROOT/data/artifacts}"
export BIOREASON_CACHE_ROOT="${BIOREASON_CACHE_ROOT:-$BIOREASON_RUNTIME_ROOT/cache}"
export WANDB_DIR="${WANDB_DIR:-$BIOREASON_RUNTIME_ROOT/wandb}"
export WEAVE_SERVER_CACHE_DIR="${WEAVE_SERVER_CACHE_DIR:-$WANDB_DIR/weave_server_cache}"
export HF_HOME="${HF_HOME:-$BIOREASON_CACHE_ROOT/huggingface}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$HF_HOME/datasets}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$BIOREASON_CACHE_ROOT/xdg}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$BIOREASON_CACHE_ROOT/triton}"
export TORCHINDUCTOR_CACHE_DIR="${TORCHINDUCTOR_CACHE_DIR:-$BIOREASON_CACHE_ROOT/torch_inductor}"
export TMPDIR="${TMPDIR:-$BIOREASON_RUNTIME_ROOT/tmp}"

mkdir -p \
  "$BIOREASON_ARTIFACTS_ROOT" \
  "$BIOREASON_CACHE_ROOT" \
  "$WANDB_DIR" \
  "$WEAVE_SERVER_CACHE_DIR" \
  "$HF_HOME" \
  "$HF_DATASETS_CACHE" \
  "$TRITON_CACHE_DIR" \
  "$TORCHINDUCTOR_CACHE_DIR" \
  "$TMPDIR"

exec "$@"
